// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ENGINE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> initApp() => RustLib.instance.api.crateApiInitApp();

Future<void> startRecording({required String subject}) =>
    RustLib.instance.api.crateApiStartRecording(subject: subject);

Future<String> stopRecording() => RustLib.instance.api.crateApiStopRecording();

Future<void> updateThermalStatus({required double batteryTemp}) =>
    RustLib.instance.api.crateApiUpdateThermalStatus(batteryTemp: batteryTemp);

Future<PlatformInt64> createFolder({required String name}) =>
    RustLib.instance.api.crateApiCreateFolder(name: name);

Future<List<(PlatformInt64, String)>> getFolders() =>
    RustLib.instance.api.crateApiGetFolders();

Future<List<(PlatformInt64, String, String, PlatformInt64)>> getNotesByFolder(
        {required PlatformInt64 folderId}) =>
    RustLib.instance.api.crateApiGetNotesByFolder(folderId: folderId);

Future<void> setCurrentFolder({PlatformInt64? folderId}) =>
    RustLib.instance.api.crateApiSetCurrentFolder(folderId: folderId);
