// This file usually generated by flutter_rust_bridge
// Mocking the Rust interface for the UI to consume.

class RustBridge {
  static Future<void> startRecording(String subject) async {
    print("BRIDGE: startRecording(subject: $subject)");
  }

  static Future<String> stopAndSummarize() async {
    print("BRIDGE: stopAndSummarize()");
    await Future.delayed(const Duration(seconds: 1));
    return "This is a simulated summary from the Rust Core (Phase 3).";
  }

  static Stream<String> transcriptionStream() async* {
    // F1: Streaming ASR
    for (int i = 0; i < 10; i++) {
        await Future.delayed(const Duration(milliseconds: 500));
        yield "Transcribed chunk $i...";
    }
  }
}
